# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78055bb2039963790b72cc53a22279368077fc7ea1d07e82ddbf090b027b0c7b5684ba25147c2524a19b1b5c73fb3f847bb52c0170037d01e872ada9aeda0273

test:
  secret_key_base: 976f1fbf1614e89e71ef0c350e830231b3989e6aff31d734daee67f723b73c89390c835c0a7c2f3775eff99612f549f3cd0cd312de9ec5236f322a51d8102f76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
