require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LabsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Lab. As you add validations to Lab, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LabsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before :each do
    @request.env["devise.mapping"] = Devise.mappings[:admin]
    @sign_in_admin = FactoryGirl.create(:admin)
    sign_in @sign_in_admin # Using factory girl as an example
  end

  describe "GET #index" do
    it "assigns all labs as @labs" do
      lab = Lab.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:labs)).to eq([lab])
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Lab" do
        expect {
          post :create, params: {lab: valid_attributes}, session: valid_session
        }.to change(Lab, :count).by(1)
      end

      it "assigns a newly created lab as @lab" do
        post :create, params: {lab: valid_attributes}, session: valid_session
        expect(assigns(:lab)).to be_a(Lab)
        expect(assigns(:lab)).to be_persisted
      end

      it "redirects to the created lab" do
        post :create, params: {lab: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Lab.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved lab as @lab" do
        post :create, params: {lab: invalid_attributes}, session: valid_session
        expect(assigns(:lab)).to be_a_new(Lab)
      end

      it "re-renders the 'new' template" do
        post :create, params: {lab: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested lab" do
        lab = Lab.create! valid_attributes
        put :update, params: {id: lab.to_param, lab: new_attributes}, session: valid_session
        lab.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested lab as @lab" do
        lab = Lab.create! valid_attributes
        put :update, params: {id: lab.to_param, lab: valid_attributes}, session: valid_session
        expect(assigns(:lab)).to eq(lab)
      end

      it "redirects to the lab" do
        lab = Lab.create! valid_attributes
        put :update, params: {id: lab.to_param, lab: valid_attributes}, session: valid_session
        expect(response).to redirect_to(lab)
      end
    end

    context "with invalid params" do
      it "assigns the lab as @lab" do
        lab = Lab.create! valid_attributes
        put :update, params: {id: lab.to_param, lab: invalid_attributes}, session: valid_session
        expect(assigns(:lab)).to eq(lab)
      end

      it "re-renders the 'edit' template" do
        lab = Lab.create! valid_attributes
        put :update, params: {id: lab.to_param, lab: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested lab" do
      lab = Lab.create! valid_attributes
      expect {
        delete :destroy, params: {id: lab.to_param}, session: valid_session
      }.to change(Lab, :count).by(-1)
    end

    it "redirects to the labs list" do
      lab = Lab.create! valid_attributes
      delete :destroy, params: {id: lab.to_param}, session: valid_session
      expect(response).to redirect_to(labs_url)
    end
  end
end
